export const ADD_CART_REQUEST = 'ADD_CART_REQUEST';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const ADD_CART_FAILURE = 'ADD_CART_FAILURE';

export const LOAD_CART_REQUEST = 'LOAD_CART_REQUEST';
export const LOAD_CART_SUCCESS = 'LOAD_CART_SUCCESS';
export const LOAD_CART_FAILURE = 'LOAD_CART_FAILURE';

export const REMOVE_CART_REQUEST = 'REMOVE_CART_REQUEST';
export const REMOVE_CART_SUCCESS = 'REMOVE_CART_SUCCESS';
export const REMOVE_CART_FAILURE = 'REMOVE_CART_FAILURE';

export const INCREASE_QTY_REQUEST = 'INCREASE_QTY_REQUEST';
export const INCREASE_QTY_SUCCESS = 'INCREASE_QTY_SUCCESS';
export const INCREASE_QTY_FAILURE = 'INCREASE_QTY_FAILURE';

export const DECREASE_QTY_REQUEST = 'DECREASE_QTY_REQUEST';
export const DECREASE_QTY_SUCCESS = 'DECREASE_QTY_SUCCESS';
export const DECREASE_QTY_FAILURE = 'DECREASE_QTY_FAILURE';

export const CHANGE_QTY_REQUEST = 'CHANGE_QTY_REQUEST';
export const CHANGE_QTY_SUCCESS = 'CHANGE_QTY_SUCCESS';
export const CHANGE_QTY_FAILURE = 'CHANGE_QTY_FAILURE';
